<a href="https://colab.research.google.com/github/evireim/Titanic_pass/blob/main/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
ds = pd.read_csv('train.csv')


In [3]:
ds_sex = ds.iloc[:, 4:5].values

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ds_sex = le.fit_transform(ds_sex)

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [5]:
ds.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
ds = ds.drop(['PassengerId', 'Name', 'Sex', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis=1)

In [7]:
X = ds.iloc[:, 1:].values
y = ds.iloc[:, 0].values

In [8]:
#print(X)

In [9]:
ds_sex = ds_sex.reshape(len(ds_sex),1)

In [10]:
X = np.concatenate((ds_sex, X), axis=1)

In [11]:
#print(X)

In [12]:
#print(y)

In [13]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:])
X[:, 1:] = imputer.transform(X[:, 1:])

In [14]:
#print(X)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [16]:
print(X_train)

[[ 1.          3.         29.69911765 23.25      ]
 [ 0.          1.         30.         56.9292    ]
 [ 0.          2.         34.         10.5       ]
 ...
 [ 1.          2.         21.         73.5       ]
 [ 0.          3.         29.69911765  7.55      ]
 [ 1.          3.         21.          8.05      ]]


In [17]:
print(X_test)

[[  0.           1.          48.          25.9292    ]
 [  1.           3.          29.69911765   7.8958    ]
 [  0.           2.          17.          10.5       ]
 [  0.           3.          29.69911765   8.1375    ]
 [  0.           2.           7.          26.25      ]
 [  1.           3.          21.           7.8542    ]
 [  1.           2.          36.5         26.        ]
 [  0.           1.          35.          53.1       ]
 [  1.           1.          28.          82.1708    ]
 [  0.           3.          29.69911765  15.5       ]
 [  1.           3.          25.           7.8958    ]
 [  0.           3.          26.           7.925     ]
 [  1.           1.          54.          51.8625    ]
 [  1.           2.          29.69911765  13.        ]
 [  0.           3.          29.69911765   7.75      ]
 [  1.           1.          28.          26.55      ]
 [  1.           3.          10.          27.9       ]
 [  1.           3.          24.          16.1       ]
 [  1.    

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train[:, 2:])
X_test_sc = sc.transform(X_test[:, 2:])

In [19]:
print(X_train)

[[ 1.          3.         29.69911765 23.25      ]
 [ 0.          1.         30.         56.9292    ]
 [ 0.          2.         34.         10.5       ]
 ...
 [ 1.          2.         21.         73.5       ]
 [ 0.          3.         29.69911765  7.55      ]
 [ 1.          3.         21.          8.05      ]]


In [20]:
print(X_train_sc)

[[-0.02810499 -0.18801432]
 [-0.00541218  0.53969044]
 [ 0.29627125 -0.46350293]
 ...
 [-0.6841999   0.89773487]
 [-0.02810499 -0.52724343]
 [-0.6841999  -0.51643995]]


In [21]:
X_train = np.concatenate((X_train[:, :2], X_train_sc), axis=1)

In [22]:
print(X_train)

[[ 1.          3.         -0.02810499 -0.18801432]
 [ 0.          1.         -0.00541218  0.53969044]
 [ 0.          2.          0.29627125 -0.46350293]
 ...
 [ 1.          2.         -0.6841999   0.89773487]
 [ 0.          3.         -0.02810499 -0.52724343]
 [ 1.          3.         -0.6841999  -0.51643995]]


In [23]:
print(X_test)

[[  0.           1.          48.          25.9292    ]
 [  1.           3.          29.69911765   7.8958    ]
 [  0.           2.          17.          10.5       ]
 [  0.           3.          29.69911765   8.1375    ]
 [  0.           2.           7.          26.25      ]
 [  1.           3.          21.           7.8542    ]
 [  1.           2.          36.5         26.        ]
 [  0.           1.          35.          53.1       ]
 [  1.           1.          28.          82.1708    ]
 [  0.           3.          29.69911765  15.5       ]
 [  1.           3.          25.           7.8958    ]
 [  0.           3.          26.           7.925     ]
 [  1.           1.          54.          51.8625    ]
 [  1.           2.          29.69911765  13.        ]
 [  0.           3.          29.69911765   7.75      ]
 [  1.           1.          28.          26.55      ]
 [  1.           3.          10.          27.9       ]
 [  1.           3.          24.          16.1       ]
 [  1.    

In [24]:
X_test = np.concatenate((X_test[:, :2], X_test_sc), axis=1)

In [25]:
print(X_test)

[[ 0.00000000e+00  1.00000000e+00  1.35216325e+00 -1.30124987e-01]
 [ 1.00000000e+00  3.00000000e+00 -2.81049867e-02 -5.19771744e-01]
 [ 0.00000000e+00  2.00000000e+00 -9.85883324e-01 -4.63502927e-01]
 [ 0.00000000e+00  3.00000000e+00 -2.81049867e-02 -5.14549344e-01]
 [ 0.00000000e+00  2.00000000e+00 -1.74009189e+00 -1.23193477e-01]
 [ 1.00000000e+00  3.00000000e+00 -6.84199895e-01 -5.20670593e-01]
 [ 1.00000000e+00  2.00000000e+00  4.84823389e-01 -1.28595215e-01]
 [ 0.00000000e+00  1.00000000e+00  3.71692104e-01  4.56953108e-01]
 [ 1.00000000e+00  1.00000000e+00 -1.56253896e-01  1.08508441e+00]
 [ 0.00000000e+00  3.00000000e+00 -2.81049867e-02 -3.55468181e-01]
 [ 1.00000000e+00  3.00000000e+00 -3.82516467e-01 -5.19771744e-01]
 [ 0.00000000e+00  3.00000000e+00 -3.07095610e-01 -5.19140821e-01]
 [ 1.00000000e+00  1.00000000e+00  1.80468839e+00  4.30214508e-01]
 [ 1.00000000e+00  2.00000000e+00 -2.81049867e-02 -4.09485554e-01]
 [ 0.00000000e+00  3.00000000e+00 -2.81049867e-02 -5.22922037e

In [26]:
#ann = tf.keras.models.Sequential()

In [27]:
#ann.add(tf.keras.layers.Dense(units = 6, activation='relu'))

In [28]:
#ann.add(tf.keras.layers.Dense(units = 6, activation='relu'))

In [29]:
#ann.add(tf.keras.layers.Dense(units = 1, activation='sigmoid'))

In [30]:
#ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [31]:
#ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

In [32]:
from sklearn.svm import SVC
classifier = SVC(C = 0.75, kernel = 'rbf', random_state = 0, gamma = 0.9)
classifier.fit(X_train, y_train)

SVC(C=0.75, gamma=0.9, random_state=0)

In [33]:
#from sklearn.tree import DecisionTreeClassifier
#classifier = DecisionTreeClassifier(criterion='entropy', random_state=0, min_samples_split=90)
#classifier.fit(X_train, y_train)

In [34]:
#from sklearn.ensemble import RandomForestClassifier
#classifier = RandomForestClassifier(n_estimators=30, criterion='entropy', random_state=0, min_samples_split=90)
#classifier.fit(X_train, y_train)

In [35]:
#from sklearn.linear_model import LogisticRegression
#classifier = LogisticRegression(random_state=0)
#classifier.fit(X_train, y_train)

In [36]:
#from sklearn.neighbors import KNeighborsClassifier
#classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
#classifier.fit(X_train, y_train)

In [37]:
#from sklearn.naive_bayes import GaussianNB
#classifier = GaussianNB()
#classifier.fit(X_train, y_train)

In [38]:
#from xgboost import XGBClassifier
#classifier = XGBClassifier()
#classifier.fit(X_train, y_train)

In [39]:
y_pred = classifier.predict(X_test)

In [40]:
#y_pred = ann.predict(X_test)
#y_pred = (y_pred > 0.5)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[95 11]
 [23 50]]


0.8100558659217877

In [42]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv=10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 81.61 %
Standard Deviation: 2.26 %


In [43]:
#from sklearn.model_selection import GridSearchCV
#parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear']},
#              {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
#grid_search = GridSearchCV(estimator = classifier, 
#                           param_grid = parameters,
#                           scoring = 'accuracy',
#                           cv = 10,
#                           n_jobs = -1)    
#grid_search.fit(X_train, y_train)
#best_accuracy = grid_search.best_score_
#best_parameters = grid_search.best_params_
#print("Accuracy: {:.2f} %".format(best_accuracy*100))
#print('Best parameters', best_parameters)