<a href="https://colab.research.google.com/github/evireim/Titanic_pass/blob/main/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [137]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [138]:
ds = pd.read_csv('train.csv')


In [139]:
ds_sex = ds.iloc[:, 4:5].values

In [140]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ds_sex = le.fit_transform(ds_sex)

/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [141]:
ds.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [142]:
ds = ds.drop(['PassengerId', 'Name', 'Sex', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis=1)

In [144]:
X = ds.iloc[:, 1:].values
y = ds.iloc[:, 0].values

In [145]:
print(X)

[[ 3.     22.      7.25  ]
 [ 1.     38.     71.2833]
 [ 3.     26.      7.925 ]
 ...
 [ 3.         nan 23.45  ]
 [ 1.     26.     30.    ]
 [ 3.     32.      7.75  ]]


In [146]:
ds_sex = ds_sex.reshape(len(ds_sex),1)

In [147]:
X = np.concatenate((ds_sex, X), axis=1)

In [148]:
print(X)

[[ 1.      3.     22.      7.25  ]
 [ 0.      1.     38.     71.2833]
 [ 0.      3.     26.      7.925 ]
 ...
 [ 0.      3.         nan 23.45  ]
 [ 1.      1.     26.     30.    ]
 [ 1.      3.     32.      7.75  ]]


In [149]:
print(y)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

In [150]:
from sklearn import impute
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:])
X[:, 1:] = imputer.transform(X[:, 1:])

In [151]:
print(X)

[[ 1.          3.         22.          7.25      ]
 [ 0.          1.         38.         71.2833    ]
 [ 0.          3.         26.          7.925     ]
 ...
 [ 0.          3.         29.69911765 23.45      ]
 [ 1.          1.         26.         30.        ]
 [ 1.          3.         32.          7.75      ]]


In [152]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [153]:
print(X_train)

[[ 1.          3.         29.69911765 23.25      ]
 [ 0.          1.         30.         56.9292    ]
 [ 0.          2.         34.         10.5       ]
 ...
 [ 1.          2.         21.         73.5       ]
 [ 0.          3.         29.69911765  7.55      ]
 [ 1.          3.         21.          8.05      ]]


In [154]:
print(X_test)

[[  0.           1.          48.          25.9292    ]
 [  1.           3.          29.69911765   7.8958    ]
 [  0.           2.          17.          10.5       ]
 [  0.           3.          29.69911765   8.1375    ]
 [  0.           2.           7.          26.25      ]
 [  1.           3.          21.           7.8542    ]
 [  1.           2.          36.5         26.        ]
 [  0.           1.          35.          53.1       ]
 [  1.           1.          28.          82.1708    ]
 [  0.           3.          29.69911765  15.5       ]
 [  1.           3.          25.           7.8958    ]
 [  0.           3.          26.           7.925     ]
 [  1.           1.          54.          51.8625    ]
 [  1.           2.          29.69911765  13.        ]
 [  0.           3.          29.69911765   7.75      ]
 [  1.           1.          28.          26.55      ]
 [  1.           3.          10.          27.9       ]
 [  1.           3.          24.          16.1       ]
 [  1.    

In [155]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train[:, 2:])
X_test_sc = sc.fit_transform(X_test[:, 2:])

In [156]:
print(X_train)

[[ 1.          3.         29.69911765 23.25      ]
 [ 0.          1.         30.         56.9292    ]
 [ 0.          2.         34.         10.5       ]
 ...
 [ 1.          2.         21.         73.5       ]
 [ 0.          3.         29.69911765  7.55      ]
 [ 1.          3.         21.          8.05      ]]


In [157]:
print(X_train_sc)

[[-0.02810499 -0.18801432]
 [-0.00541218  0.53969044]
 [ 0.29627125 -0.46350293]
 ...
 [-0.6841999   0.89773487]
 [-0.02810499 -0.52724343]
 [-0.6841999  -0.51643995]]


In [158]:
X_train = np.concatenate((X_train[:, :2], X_train_sc), axis=1)

In [159]:
print(X_train)

[[ 1.          3.         -0.02810499 -0.18801432]
 [ 0.          1.         -0.00541218  0.53969044]
 [ 0.          2.          0.29627125 -0.46350293]
 ...
 [ 1.          2.         -0.6841999   0.89773487]
 [ 0.          3.         -0.02810499 -0.52724343]
 [ 1.          3.         -0.6841999  -0.51643995]]


In [160]:
print(X_test)

[[  0.           1.          48.          25.9292    ]
 [  1.           3.          29.69911765   7.8958    ]
 [  0.           2.          17.          10.5       ]
 [  0.           3.          29.69911765   8.1375    ]
 [  0.           2.           7.          26.25      ]
 [  1.           3.          21.           7.8542    ]
 [  1.           2.          36.5         26.        ]
 [  0.           1.          35.          53.1       ]
 [  1.           1.          28.          82.1708    ]
 [  0.           3.          29.69911765  15.5       ]
 [  1.           3.          25.           7.8958    ]
 [  0.           3.          26.           7.925     ]
 [  1.           1.          54.          51.8625    ]
 [  1.           2.          29.69911765  13.        ]
 [  0.           3.          29.69911765   7.75      ]
 [  1.           1.          28.          26.55      ]
 [  1.           3.          10.          27.9       ]
 [  1.           3.          24.          16.1       ]
 [  1.    

In [161]:
X_test = np.concatenate((X_test[:, :2], X_test_sc), axis=1)

In [162]:
print(X_test)

[[ 0.00000000e+00  1.00000000e+00  1.68087607e+00 -1.18770935e-01]
 [ 1.00000000e+00  3.00000000e+00  1.25938848e-01 -4.12983294e-01]
 [ 0.00000000e+00  2.00000000e+00 -9.53043596e-01 -3.70496141e-01]
 [ 0.00000000e+00  3.00000000e+00  1.25938848e-01 -4.09039993e-01]
 [ 0.00000000e+00  2.00000000e+00 -1.80269510e+00 -1.13537129e-01]
 [ 1.00000000e+00  3.00000000e+00 -6.13182994e-01 -4.13661992e-01]
 [ 1.00000000e+00  2.00000000e+00  7.03776841e-01 -1.17615843e-01]
 [ 0.00000000e+00  1.00000000e+00  5.76329115e-01  3.24516806e-01]
 [ 1.00000000e+00  1.00000000e+00 -1.84269392e-02  7.98802777e-01]
 [ 0.00000000e+00  3.00000000e+00  1.25938848e-01 -2.88921851e-01]
 [ 1.00000000e+00  3.00000000e+00 -2.73322391e-01 -4.12983294e-01]
 [ 0.00000000e+00  3.00000000e+00 -1.88357241e-01 -4.12506900e-01]
 [ 1.00000000e+00  1.00000000e+00  2.19066698e+00  3.04327169e-01]
 [ 1.00000000e+00  2.00000000e+00  1.25938848e-01 -3.29708996e-01]
 [ 0.00000000e+00  3.00000000e+00  1.25938848e-01 -4.15362000e

In [163]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state=0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [164]:
#from sklearn.tree import DecisionTreeClassifier
#classifier = DecisionTreeClassifier(criterion='entropy', random_state=0, min_samples_split=90)
#classifier.fit(X_train, y_train)

In [165]:
#from sklearn.ensemble import RandomForestClassifier
#classifier = RandomForestClassifier(n_estimators=30, criterion='entropy', random_state=0, min_samples_split=90)
#classifier.fit(X_train, y_train)

In [166]:
#from sklearn.linear_model import LogisticRegression
#classifier = LogisticRegression(random_state=0)
#classifier.fit(X_train, y_train)

In [167]:
#from sklearn.neighbors import KNeighborsClassifier
#classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
#classifier.fit(X_train, y_train)

In [168]:
#from sklearn.naive_bayes import GaussianNB
#classifier = GaussianNB()
#classifier.fit(X_train, y_train)

In [169]:
y_pred = classifier.predict(X_test)

In [170]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[91 15]
 [22 51]]


0.7932960893854749